/**
 * This file was generated by Craft Solutions team, and the code
 * bellow should not be copied, transfered, or tamper with in part
 * or in total without the express authorization of the directing
 * parties of Craft or the authoring clients defined by Craft.
 *
 * Fail to complain to these requirements make the party subject
 * for legal actions and prosecution. For more details contact
 * Craft Solutions at contact@craft-solutions.com.
 */
package com.craft.anje.avatarsocial.ut;

import java.io.BufferedReader;
import java.io.InputStreamReader;
import java.util.StringTokenizer;

/**
 * <p> TODO: Implement </p>
 *
 * Created on 22/11/2014
 * @version CRAFT-PBCA-1.0
 * @author <a href="mailto:joao.rios@craft-solutions.com">Joao Gonzalez</a>
 */
public class UserDBGenerator {

	/**
	 * 
	 */
	public UserDBGenerator() {
		// TODO Auto-generated constructor stub
	}

	/**
	 * @param args
	 */
	public static void main(String[] args) {
		String path = "Guia_Acesso_Parceiro_AVATARES.csv";
		BufferedReader reader = null;
		try {
			StringBuffer buf = new StringBuffer("[");
			reader =  new BufferedReader(new InputStreamReader(UserDBGenerator.class.getResourceAsStream(path), "UTF8"));
			
			String read;
			while ((read=reader.readLine())!=null) {
				StringTokenizer tokens = new StringTokenizer(read, ";");
				if (tokens.countTokens()>=5) {
					String id = tokens.nextToken();
					String name = tokens.nextToken();
					String userid=tokens.nextToken();
					String password=tokens.nextToken();
					String stand = tokens.nextToken();
					String email = tokens.hasMoreTokens()?tokens.nextToken():null;
					
					// Writes the data
					buf.append ("\n\t{'id':");
					buf.append (Integer.parseInt(id));
					buf.append (", 'name': '");
					buf.append (name);
					buf.append ("', 'userid': '");
					buf.append (userid);
					buf.append ("', 'password': '");
					buf.append (password);
					buf.append ("', 'email': '");
					buf.append (email);
					buf.append ("'},");
				}
			}
			buf.append("\n]");
			
			String content = buf.toString();
			// Writes the output
			System.out.println(content);
		}
		catch (Exception ex) {
			ex.printStackTrace(System.err);
		}
		finally {
			try {
				reader.close();
			}
			catch (Exception ex) {}
		}
	}

}
