/**
 * This file was generated by Craft Solutions team, and the code
 * bellow should not be copied, transfered, or tamper with in part
 * or in total without the express authorization of the directing
 * parties of Craft or the authoring clients defined by Craft.
 *
 * Fail to complain to these requirements make the party subject
 * for legal actions and prosecution. For more details contact
 * Craft Solutions at contact@craft-solutions.com.
 */
package com.craft.anje.avatarsocial;

import javax.servlet.ServletException;

/**
 * <p> Exception class for all the Avatar running operations. </p>
 *
 * Created on 20/11/2014
 * @version CRAFT-PBCA-1.0
 * @author <a href="mailto:joao.rios@craft-solutions.com">Joao Gonzalez</a>
 */
public class AvatarException extends ServletException {
	private static final long serialVersionUID = 1318429522428798261L;

	/**
	 * Default constructor
	 */
	public AvatarException() {
	}

	/**
	 * @param message
	 */
	public AvatarException(String message, int rc) {
		super(message);
		setRC(rc);
	}

	/**
	 * @param rootCause
	 */
	public AvatarException(Throwable rootCause, int rc) {
		super(rootCause);
		
		setRC(rc);
	}

	/**
	 * @param message
	 * @param rootCause
	 */
	public AvatarException(String message, Throwable rootCause, int rc) {
		super(message, rootCause);

		setRC(rc);
	}
	
	/**
	 * @see java.lang.Throwable#getMessage()
	 */
	public String getMessage () {
		return super.getMessage()!=null?super.getMessage().concat(" -> RC: "+getRC()):"Internal Processing Error - null";
	}

	/**
	 * <p> Returns the return code of the operation. </p>
	 */
	public int getRC () {
		return mReturnCode;
	}
	private void setRC (int rc) {
		mReturnCode = rc;
	}
	
	// class properties
	private int mReturnCode;
}
