/**
 * This file was generated by Craft Solutions team, and the code
 * bellow should not be copied, transfered, or tamper with in part
 * or in total without the express authorization of the directing
 * parties of Craft or the authoring clients defined by Craft.
 *
 * Fail to complain to these requirements make the party subject
 * for legal actions and prosecution. For more details contact
 * Craft Solutions at contact@craft-solutions.com.
 */
package com.craft.anje.avatarsocial;

/**
 * <p> Constants to be used within the framework </p>
 *
 * Created on 20/11/2014
 * @version CRAFT-PBCA-1.0
 * @author <a href="mailto:joao.rios@craft-solutions.com">Joao Gonzalez</a>
 */
public interface IConstants {

	/**
	 * <p> Defines the name of the session attribute that have the internal session token 
	 */
	public static final String SESSION_TOKEN = "session-token";

	/**
	 * <p> The request parameter name of the file content sent by the client. </p>
	 */
	public static final String REQUEST_FILECONTENT = "file_cnt";
	
	/**
	 * Property key information about the number of batch files to stream 
	 */
	public static final String PROPERTY_STREAM_BATCH = "numberOfBatchFiles";
	/**
	 * Property key that specifies the file default content types
	 */
	public static final String PROPERTY_FILE_CONTENTTYPE = "fileContentType";
	/**
	 * Property key that specifies the file extension.
	 */
	public static final String PROPERTY_FILE_EXT = "fileExtention";
	/**
	 * Defines the minimum buffer size
	 */
	public static final String PROPERTY_MINBUF = "minExecBuffer";
	/**
	 * Verifies for how long should the user waits to verify if the minimum amount of cached video sizes was reached.
	 */
	public static final String PROPERTY_BUFVERIFY_WAIT = "bufferWaitTimeVerification";
}
