/**
 * This file was generated by Craft Solutions team, and the code
 * bellow should not be copied, transfered, or tamper with in part
 * or in total without the express authorization of the directing
 * parties of Craft or the authoring clients defined by Craft.
 *
 * Fail to complain to these requirements make the party subject
 * for legal actions and prosecution. For more details contact
 * Craft Solutions at contact@craft-solutions.com.
 */
package com.craft.anje.avatarsocial;

/**
 * <p> Return codes for the exceptions </p>
 *
 * Created on 20/11/2014
 * @version CRAFT-PBCA-1.0
 * @author <a href="mailto:joao.rios@craft-solutions.com">Joao Gonzalez</a>
 */
public interface IRC {
	/**
	 * Indetify that none error has happened: 0
	 */
	public static final int ERR_NONE = 0;
	/**
	 * An unknown error occurred: 5000.
	 */
	public static final int ERR_UNKNOWN = 5000;
	/**
	 * Security constraint validation failed: 5001.
	 */
	public static final int ERR_SECURITY=5001;
	/**
	 * Need to generate new token: 5002
	 */
	public static final int ERR_NEWTOKEN=5002;
}
